#!/bin/sh
#---Autostart
sxhkd &
picom &
redshift &
desktop

bspc rule -r "*"

# We look for a non-laptop monitor to use for default, but use the laptop
# screen (LVDS) if there's nothing else. This is because I assume that if you
# have an extra screen attached to a laptop, you want to use that.
mainmonitor="$(bspc query --monitors --names | grep -v LVDS | head -n 1)"

if ! echo "$mainmonitor" | grep LVDS >/dev/null 2>&1; then
	xrandr --output "$mainmonitor" --auto --output LVDS1 --off
fi

#### MONITORS ####
bspc monitor HDMI-A-0 -d 1 2 3 4 5 6 7 8 9
bspc monitor HDMI-A-1 -d 1 2 3 4 5 6 7 8 9
bspc monitor DVI-D-0 -d 1 2 3 4 5 6 7 8 9

# If you want a multi-monitor display or something else, I leave that to you to
# arrange. I have this sensible default for most people's use cases.


bspc config border_width 1
bspc config window_gap 20
bspc config top_padding 24	# top_padding I set equal to polybar's height

bspc config focus_follows_pointer	true
bspc config borderless_monocle          true
bspc config gapless_monocle             true

dropdownname="dropdown"
bspc query -N -n .hidden >/dev/null || setsid $TERMINAL -n "$dropdownname" -e dropdown >/dev/null 2>&1 &
bspc rule -a St:$dropdownname hidden=on
bspc rule -a St:$dropdownname sticky=on
bspc rule -a St:$dropdownname state=floating

bspc config external_rules_command "$(which floaters)"

# Coloring
bspc config normal_border_color		"#4c566a"
bspc config active_border_color		"#1e1e1e"
bspc config focused_border_color	"#ffd7a7"
bspc config presel_feedback_color	"#5e81ac"
bspc config urgent_border_color 	"#dd2727"

# polybar hidden when fullscreen for vlc, youtube, mpv ...
xdo below -t $(xdo id -n root) $(xdo id -a polybar-main_HDMI-A-0)
xdo below -t $(xdo id -n root) $(xdo id -a polybar-main_HDMI-A-1)
xdo below -t $(xdo id -n root) $(xdo id -a polybar-main_DVI-D-0)

# Window rules
bspc rule -a arandr state=floating
#size with xdo resize? xdo resize -w 800 -h 600
