#!/usr/bin/env sh

EDIT() { $TERMINAL -e zsh -c "sleep 0.03 && nvim $file" ;}
SCRIPTS() { input=$(ls ~/Scripts | dmenu -i -p 'Edit script:')  ;}

choices="\
scripts
sxhkd
spectrwm
bookmarks
programs
vim
alacritty
zsh
aliasrc
mutt
polybar
vifm
zprofile
xinit
picom
bash
xmonad
bspwm
"

chosen=$(echo  "$choices"| dmenu -i -p 'Edit config:')

case "$chosen" in
	bash) file="$HOME/.bashrc" ;;
	zsh) file="$HOME/.zshrc" ;;
	aliasrc) file="$HOME/.config/aliasrc" ;;
	zprofile) file="$HOME/.zprofile" ;;
	xinit) file="$HOME/.xinitrc" ;;
	bspwm) file="$HOME/.config/bspwm/bspwmrc" ;;
	sxhkd) file="$HOME/.config/sxhkd/sxhkdrc" ;;
	vim) file="$HOME/.config/nvim/init.vim" ;;
	vifm) file="$HOME/.config/vifm/vifmrc" ;;
	picom) file="$HOME/.config/picom/picom.conf" ;;
	programs) file="$HOME/Nextcloud/minimal_install.sh" ;;
	bookmarks) file="$HOME/Nextcloud/bookmarks" ;;
	mutt) file="$HOME/.config/mutt/muttrc" ;;
	polybar) file="$HOME/.config/polybar/config" ;;
	alacritty) file="$HOME/.config/alacritty/alacritty.yml" ;;
	xmonad) file="$HOME/.xmonad/xmonad.hs" ;;
	spectrwm) file="$HOME/.spectrwm.conf" ;;

	scripts) SCRIPTS && file=$(ls -d ~/Scripts/* | grep "$input") ;;
esac

[ -z $file] || EDIT
