#!/usr/bin/env sh

list=$(find -L $HOME/Projects/ -regex ".*\.[Rr]\(md\)?")
input=$(echo "$list" | awk -F "/" '{print $NF}' | sort | dmenu -i -p 'Edit project:')
file=$(echo "$list" | grep "$input$")

[ -z "$input" ] || $TERMINAL -e nvim "$file"
