#!/usr/bin/env sh

if [ -z "$(pgrep -a polybar)" ]; then
  polybar --reload mainbar-spectrwm -c ~/.config/polybar/config &
  polybar --reload leftbar -c ~/.config/polybar/config #&
  # polybar --reload rightbar -c ~/.config/polybar/config
else
  killall -q polybar
fi

# while pgrep -u $UID -x polybar > /dev/null; do sleep 1; done

# if type "xrandr" > /dev/null; then
#       for m in $(xrandr --query | grep " connected" | cut -d" " -f1); do
#         MONITOR=$m polybar --reload mainbar-spectrwm -c ~/.config/polybar/config &
#       done
#     else
#     polybar --reload mainbar-spectrwm -c ~/.config/polybar/config &
#     fi
